apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-java
  namespace: apps
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-java
  template:
    metadata:
      labels:
        app: app-java
    spec:
      containers:
      - name: java-app
        image: karimanmahmoud/app-java:v25
        ports:
        - containerPort: 8080



