apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
      - name: java-app
        image: karimanmahmoud/my-java-app:{{TAG}}
        ports:
        - containerPort: 8080
