apiVersion: v1
kind: Service
metadata:
  name: app-java
  namespace: apps
spec:
  type: NodePort
  selector: 
    app: app-java
  ports:
  - name: http
    port: 80
    targetPort: 8080

